---

# Cluster Configurations
cluster_name: ''
cluster_provisioning_vars_inventory: "{{ cluster_name }}"
cluster_aws_region: ''
cluster_aws_access_key: ''
cluster_aws_secret_access_key: ''

# Integreatly Configurations
integreatly_install_type: 'poc'

# Workflow Job Template
integreatly_workflow_install_job_template_name: 'Integreatly Install Workflow'
integreatly_workflow_install_job_template_desc: 'Workflow for Installing Integreatly on Openshift'
integreatly_workflow_install_job_template_organization: "{{ tower_organization }}"
integreatly_workflow_install_job_template_concurrency: true

integreatly_workflow_uninstall_job_template_name: 'Integreatly Uninstall Workflow'
integreatly_workflow_uninstall_job_template_desc: 'Workflow for Uninstalling Integreatly on Openshift'
integreatly_workflow_uninstall_job_template_organization: "{{ tower_organization }}"
integreatly_workflow_uninstall_job_template_concurrency: true

# Integreatly Credentials
integreatly_credential_bundle_github_name: "tower_github_scm"
integreatly_credential_bundle_github_desc: "SCM credentials for Integreatly project"
integreatly_credential_bundle_github_kind: 'scm'

# Integreatly Job Templates: Install
integreatly_job_template_bootstrap_install_name: 'Integreatly Bootstrap Install Template'
integreatly_job_template_bootstrap_install_desc: 'Job for bootstrapping integreatly cluster resources'
integreatly_job_template_bootstrap_install_type: 'run'
integreatly_job_template_bootstrap_install_playbook: 'playbooks/bootstrap_integreatly_install.yml'
integreatly_job_template_bootstrap_install_credentials: "{{ tower_credential_bundle_default_name }}"
integreatly_job_template_bootstrap_install_concurrency: true

integreatly_job_template_deploy_name: 'Integreatly Deploy Template'
integreatly_job_template_deploy_desc: 'Job for deploying Integreatly on Openshift'
integreatly_job_template_deploy_type: 'run'
integreatly_job_template_deploy_playbook: 'playbooks/install.yml'
integreatly_job_template_deploy_credentials: "{{ tower_credential_bundle_default_name }}"
integreatly_job_template_deploy_concurrency: true

# Integreatly Job Templates: Uninstall
integreatly_job_template_uninstall_name: 'Integreatly Uninstall Template'
integreatly_job_template_uninstall_desc: 'Job for uninstalling Integreatly on Openshift'
integreatly_job_template_uninstall_type: 'run'
integreatly_job_template_uninstall_playbook: 'playbooks/uninstall.yml'
integreatly_job_template_uninstall_credentials: "{{ tower_credential_bundle_default_name }}"
integreatly_job_template_uninstall_concurrency: true

integreatly_job_template_bootstrap_uninstall_name: 'Integreatly Bootstrap Uninstall Template'
integreatly_job_template_bootstrap_uninstall_desc: 'Job for bootstrapping resources for Integreatly uninstall'
integreatly_job_template_bootstrap_uninstall_type: 'run'
integreatly_job_template_bootstrap_uninstall_playbook: 'playbooks/bootstrap_integreatly_uninstall.yml'
integreatly_job_template_bootstrap_uninstall_credentials: "{{ tower_credential_bundle_default_name }}"
integreatly_job_template_bootstrap_uninstall_concurrency: true

integreatly_job_template_cleandown_name: 'Integreatly Clean Down Template'
integreatly_job_template_cleandown_desc: 'Job for cleaning down Integreatly resources'
integreatly_job_template_cleandown_type: 'run'
integreatly_job_template_cleandown_playbook: 'playbooks/bootstrap_integreatly_cleandown.yml'
integreatly_job_template_cleandown_credentials: "{{ tower_credential_bundle_default_name }}"

# Integreatly Projects
integreatly_project_install_scm_branch: ''
integreatly_project_install_name: "integreatly-install-{{ integreatly_project_install_scm_branch }}"
integreatly_project_install_desc: "Integreatly Project for Branch: {{ integreatly_project_install_scm_branch }}"
integreatly_project_install_scm_type: git
integreatly_project_install_scm_clean: true
integreatly_project_install_scm_url: ''
integreatly_project_install_scm_update_on_launch: false
integreatly_project_install_scm_delete_on_update: true

integreatly_project_uninstall_scm_branch: ''
integreatly_project_uninstall_name: "integreatly-uninstall-{{ integreatly_project_uninstall_scm_branch }}"
integreatly_project_uninstall_desc: "Integreatly Project for Branch: {{ integreatly_project_uninstall_scm_branch }}"
integreatly_project_uninstall_scm_type: git
integreatly_project_uninstall_scm_clean: true
integreatly_project_uninstall_scm_url: ''
integreatly_project_uninstall_scm_update_on_launch: false
integreatly_project_uninstall_scm_delete_on_update: true

# Integreatly Inventories
integreatly_inventory_name: "{{ cluster_name }}"
integreatly_inventory_desc: "Integreatly Inventory: {{ cluster_name }}"

# Integreatly Sources
integreatly_inventory_source_aws_name: "{{ cluster_name }}-inventory-source-aws"
integreatly_inventory_source_aws_type: 'ec2'
integreatly_inventory_source_aws_update_on_launch: false
integreatly_inventory_source_aws_overwrite: true
integreatly_inventory_source_aws_overwrite_vars: true
integreatly_inventory_source_aws_credentials: ''
integreatly_inventory_source_aws_regions: 'All'
integreatly_inventory_source_aws_instance_filters: "tag:clusterid={{ cluster_name }}"

integreatly_inventory_source_project_name: "{{ cluster_name }}-inventory-source-project-{{ integreatly_project_install_name }}"
integreatly_inventory_source_project_type: 'scm'
integreatly_inventory_source_project_path: "inventories/{{ integreatly_install_type }}.template"
integreatly_inventory_source_project_update_on_launch: false
integreatly_inventory_source_project_overwrite: true
integreatly_inventory_source_project_overwrite_vars: true

# Integreatly Groups
integreatly_group_master_name: 'master'
integreatly_group_master_desc: "Master group: {{ cluster_name }}"
integreatly_group_master_overwrite: true
integreatly_group_master_overwrite_vars: true
integreatly_group_master_update_on_launch: false
integreatly_group_master_aws_name: 'tag_host_type_master'

integreatly_group_local_name: 'local'
integreatly_group_local_desc: "Local group: {{ cluster_name }}"
integreatly_group_local_overwrite: true
integreatly_group_local_overwrite_vars: true
integreatly_group_local_update_on_launch: false

# Integreatly Hosts
integreatly_host_local_name: 'localhost'
integreatly_host_local_desc: "Localhost: {{ cluster_name }}"

# Integreatly Survey
integreatly_install_survey_aws_accounts: []

# OSD install
integreatly_osd_install_branch: "{{ integreatly_version }}"
integreatly_osd_project_install_scm_url: "git@github.com:integr8ly/installation.git"
integreatly_osd_install_desc: "Integreatly Project: {{ integreatly_osd_install_branch }}"
integreatly_osd_install_org: integreatly
integreatly_osd_install_inventory: OSD_Tower_Install_Inventory
integreatly_osd_install_source_name:  installation-project-source
integreatly_osd_install_source_path: "inventories/osd.template"
integreatly_osd_install_name: "Integreatly_Install_Template_[OSD]"
integreatly_osd_bootstrap_name: "Integreatly_Bootstrap_Template_[OSD]"
integreatly_osd_workflow_name: "Integreatly_Bootstrap_and_Install_[OSD]"
integreatly_osd_workflow_description: "Workflow to configure and install integreatly on an OSD cluster"
integreatly_osd_source_project_update_on_launch: true
integreatly_osd_install_workflow_job_concurrency: True

# OSD uninstall
integreatly_osd_uninstall_branch: "{{ integreatly_version }}"
integreatly_osd_project_uninstall_scm_url: "git@github.com:integr8ly/installation.git"
integreatly_osd_uninstall_desc: "Integreatly Project: {{ integreatly_osd_uninstall_branch }}"
integreatly_osd_uninstall_org: integreatly
integreatly_osd_uninstall_inventory: OSD_Tower_Uninstall_Inventory
integreatly_osd_uninstall_source_name:  uninstall-project-source
integreatly_osd_uninstall_source_path: "inventories/osd.template"
integreatly_osd_uninstall_name: "Integreatly_Uninstall_Template_[OSD]"
integreatly_osd_uninstall_bootstrap_name: "Integreatly_Bootstrap_Uninstall_Template_[OSD]"
integreatly_osd_uninstall_workflow_name: "Integreatly_Bootstrap_and_Uninstall_[OSD]"
integreatly_osd_uninstall_workflow_description: "Workflow to uninstall integreatly from an OSD cluster"
integreatly_osd_uninstall_source_project_update_on_launch: true
integreatly_osd_uninstall_workflow_job_concurrency: True

# OSD upgrade
integreatly_osd_update_branch: "{{ integreatly_version }}"
integreatly_osd_upgrade_bootstrap_name: "Integreatly_Upgrade_Bootstrap_Template_[OSD]"
integreatly_osd_upgrade_source_name: update-project-source
integreatly_osd_upgrade_name: "Integreatly_Upgrade_[OSD]"
integreatly_osd_upgrade_workflow_name: "Integreatly_Bootstrap_and_Upgrade_[OSD]"
integreatly_osd_upgrade_desc: "Workflow to upgrade integreatly on an OSD cluster"
integreatly_osd_update_inventory: OSD_update_inventory
integreatly_osd_upgrade_workflow_job_concurrency: True

# CS SRE Projects
cssre_ansible_ops_project_scm_branch: "prod"
cssre_ansible_ops_project_name: "rhmi-ansible-ops"
cssre_ansible_ops_project_desc: "{{ cssre_ansible_ops_project_name }} Project for Branch: {{ cssre_ansible_ops_project_scm_branch }}"
cssre_ansible_ops_project_scm_type: git
cssre_ansible_ops_project_scm_clean: true
cssre_ansible_ops_project_scm_url: 'git@github.com:rh-cssre/rhmi-ansible-ops.git'
cssre_ansible_ops_project_scm_update_on_launch: true
cssre_ansible_ops_project_scm_delete_on_update: true

cssre_rhmi_pingdom_scm_branch: "prod"
cssre_rhmi_pingdom_name: "rhmi-pingdom"
cssre_rhmi_pingdom_desc: "{{ cssre_rhmi_pingdom_name }} Project for Branch: {{ cssre_rhmi_pingdom_scm_branch }}"
cssre_rhmi_pingdom_scm_type: git
cssre_rhmi_pingdom_scm_clean: true
cssre_rhmi_pingdom_scm_url: 'git@github.com:rh-cssre/rhmi-pingdom.git'
cssre_rhmi_pingdom_scm_update_on_launch: true
cssre_rhmi_pingdom_scm_delete_on_update: true

# CS SRE Jobs
rhmi_pingdom_provision_name: "Provision_Pingdom_Checks_[OSD]"
rhmi_pingdom_provision_desc: "Job for creating pingdom checks for RHMI on OSD"
rhmi_pingdom_extra_vars_file_path: '/tmp/rhmi_pingdom_extra_vars.yml'

rhmi_ssh_tunnel_create_name: "Integreatly_Create_SSH_Tunnel_[OSD]"
rhmi_ssh_tunnel_create_desc: "Creates SSH Tunnel to OCP master node"
rhmi_ssh_tunnel_extra_vars_file_path: '/tmp/rhmi_ssh_tunnel_extra_vars.yml'

rhmi_ssh_tunnel_delete_name: "Integreatly_Delete_SSH_Tunnel_[OSD]"
rhmi_ssh_tunnel_delete_desc: "Deletes SSH Tunnel to OCP master node"

rhmi_post_install_housekeeping_name: "Integreatly_Post_Install_HouseKeeping_[OSD]"
rhmi_post_install_housekeeping_desc: "Completes all needed CS SRE housekeeping like creating pagerduty and configuring alertmanager"
rhmi_post_install_housekeeping_extra_vars_file_path: '/tmp/rhmi_post_install_housekeeping_extra_vars.yml'

rhmi_post_uninstall_housekeeping_name: "Integreatly_Post_Uninstall_HouseKeeping_[OSD]"
rhmi_post_uninstall_housekeeping_desc: "Deletes services like pagerduty, DMS and sengrid for a decommissioned cluster."
rhmi_post_uninstall_housekeeping_extra_vars_file_path: '/tmp/rhmi_post_uninstall_housekeeping_extra_vars.yml'

# OSD CVE Rollouts
integreatly_osd_cve_rollout_workflow_name: "Integreatly_CVE_rollout_[OSD]"
integreatly_osd_cve_rollout_workflow_desc: "Workflow for rolling out CVEs to OSD"
integreatly_osd_cve_rollout_workflow_job_concurrency: True

integreatly_osd_cve_rollout_job_template_name: "Integreatly_CVE_Rollout_Job_Template_[OSD]"
integreatly_osd_cve_rollout_job_template_desc: "Job template for rolling out CVEs to OSD"
integreatly_osd_cve_rollout_job_template_concurrency: True

integreatly_osd_cve_rollout_bootstrap_name: "Integreatly_CVE_Bootstrap_Template_[OSD]"
integreatly_osd_cve_rollout_bootstrap_desc: "Job template for bootstrapping CVE rollout jobs on OSD"
integreatly_osd_cve_rollout_bootstrap_concurrency: True

integreatly_osd_cve_rollout_project_branch: "{{ integreatly_version }}"
integreatly_osd_cve_rollout_project_name: "integreatly-cve-{{ integreatly_osd_cve_rollout_project_branch }}"
integreatly_osd_cve_rollout_project_desc: "Project for CVE rollouts"
integreatly_osd_cve_rollout_project_scm_type: git
integreatly_osd_cve_rollout_project_scm_url: 'git@github.com:integr8ly/installation.git'
integreatly_osd_cve_rollout_project_scm_clean: true
integreatly_osd_cve_rollout_project_scm_update_on_launch: false
integreatly_osd_cve_rollout_project_scm_delete_on_update: true

integreatly_osd_cve_rollout_org: integreatly
integreatly_osd_cve_rollout_inventory_name: OSD_cve_inventory
integreatly_osd_cve_rollout_inventory_desc: "Inventory for OSD CVE Rollouts"
integreatly_osd_cve_rollout_product_tags: ''

integreatly_osd_cve_rollout_source_name: cve-project-source
integreatly_osd_cve_rollout_source_project_on_launch: true
integreatly_osd_cve_rollout_source_path: "inventories/osd.template"
