---
- name: Configure Openshift authenticate job template
  tower_job_template:
    name: "{{ cluster_job_template_openshift_auth_name }}"
    description: "{{ cluster_job_template_openshift_auth_desc }}"
    job_type: "{{ cluster_job_template_openshift_auth_type }}"
    playbook: "{{ cluster_job_template_openshift_auth_playbook }}"
    project: "{{ cluster_job_template_openshift_auth_project }}"
    credential: "{{ tower_credential_bundle_default_name }}"
    extra_vars_path: "files/openshift_tower_auth.yml"
    state: present
    inventory: "Provisioning_inventory"

- name: Configure generate inventory job template
  tower_job_template:
    name: "{{ cluster_job_template_generate_inventory_name }}"
    description: "{{ cluster_job_template_generate_inventory_desc }}"
    job_type: "{{ cluster_job_template_generate_inventory_type }}"
    playbook: "{{ cluster_job_template_generate_inventory_playbook }}"
    project: "{{ cluster_job_template_generate_inventory_project }}"
    credential: "{{ tower_credential_bundle_default_name }}"
    state: present
    inventory: "Provisioning_inventory"

- name: Add Custom Credential
  command: tower-cli credential create --name "le_privatekey" --credential-type "LE_privatekey" --inputs "{'le_key':'{{ letsencrypt_private_key }}'}" --organization "{{ tower_organization }}"
  no_log: true
  ignore_errors: true

- name: Configure pre-flight job template
  tower_job_template:
    name: "{{ cluster_job_template_preflight_name }}"
    description: "{{ cluster_job_template_preflight_desc }}"
    job_type: "{{ cluster_job_template_preflight_type }}"
    playbook: "{{ cluster_job_template_preflight_playbook }}"
    project: "{{ cluster_job_template_preflight_project }}"
    credential: "{{ tower_credential_bundle_default_name }}"
    state: present
    inventory: "Provisioning_inventory"

- name: Associate additional credentials
  shell: tower-cli job_template associate_credential --job-template "{{ cluster_job_template_preflight_name }}" --credential "{{ cluster_job_template_preflight_credentials }}"

- name: Configure prerequisites job template
  tower_job_template:
    name: "{{ cluster_job_template_prerequisites_name }}"
    description: "{{ cluster_job_template_prerequisites_desc }}"
    job_type: "{{ cluster_job_template_prerequisites_type }}"
    playbook: "{{ cluster_job_template_prerequisites_playbook }}"
    project: "{{ cluster_job_template_prerequisites_project }}"
    credential: "{{ tower_credential_bundle_default_name }}"
    state: present
    inventory: "Provisioning_inventory"

- name: Associate additional credentials
  shell: tower-cli job_template associate_credential --job-template "{{ cluster_job_template_prerequisites_name }}" --credential "{{ cluster_job_template_prerequisites_credentials }}"

- name: Configure provision install job template
  tower_job_template:
    name: "{{ cluster_job_template_install_name }}"
    description: "{{ cluster_job_template_install_desc }}"
    job_type: "{{ cluster_job_template_install_type }}"
    playbook: "{{ cluster_job_template_install_playbook }}"
    project: "{{ cluster_job_template_install_project }}"
    credential: "{{ tower_credential_bundle_default_name }}"
    state: present
    inventory: "Provisioning_inventory"

- name: Associate additional credentials
  shell: tower-cli job_template associate_credential --job-template "{{ cluster_job_template_install_name }}" --credential "{{ cluster_credential_bundle_aws_name }}"

- name: Associate additional credentials
  shell: tower-cli job_template associate_credential --job-template "{{ cluster_job_template_install_name }}" --credential "{{ cluster_job_template_install_credentials }}"

- name: Configure post-install job template
  tower_job_template:
    name: "{{ cluster_job_template_post_install_name }}"
    description: "{{ cluster_job_template_post_install_desc }}"
    job_type: "{{ cluster_job_template_post_install_type }}"
    playbook: "{{ cluster_job_template_post_install_playbook }}"
    project: "{{ cluster_job_template_post_install_project }}"
    credential: "{{ tower_credential_bundle_default_name }}"
    state: present
    inventory: "Provisioning_inventory"

- name: "Create workflow: {{ cluster_workflow_job_template_name }}"
  tower_workflow_template:
    name:  "{{ cluster_workflow_job_template_name }}"
    description: "{{ cluster_workflow_job_template_desc }}"
    state: present
    organization: "{{ cluster_workflow_job_template_organization }}"

- name: Create workflow schema
  template:
    src: workflow_schema.yml.j2
    dest: "cluster_workflow_schema.yml"

- name: "Update Workflow job template with survey"
  shell: "tower-cli workflow modify --name=\"{{ cluster_workflow_job_template_name }}\" --survey-enabled=true --survey-spec='@{{ role_path }}/templates/workflow_survey.json'"

- name: "Update Workflow job template with schema"
  shell: "tower-cli workflow schema \"{{ cluster_workflow_job_template_name }}\" @cluster_workflow_schema.yml"
